/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/grequests.py:22: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['aiohttp.web_runner (/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiohttp/web_runner.py)', 'aiohttp.client (/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiohttp/client.py)', 'aiohttp.client_exceptions (/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiohttp/client_exceptions.py)', 'aiohttp.web (/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiohttp/web.py)', 'aiohttp.client_reqrep (/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py)', 'aiohttp.connector (/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiohttp/connector.py)']. 
  curious_george.patch_all(thread=False, select=False)
2023-09-13 00:12:32,120 - INFO - executor.py:362 - Bot: NotOnlyFans [@NonOnlyFansBot]
2023-09-13 00:12:32,230 - WARNING - executor.py:358 - Updates were skipped successfully.
2023-09-13 00:12:32,230 - INFO - dispatcher.py:358 - Start polling.
2023-09-13 00:16:49,741 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-150' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:17:02,468 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-153' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:17:23,670 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-173' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:17:29,312 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-176' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:18:10,179 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-212' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:18:32,772 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-235' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:18:55,451 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-259' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
2023-09-13 00:18:57,968 - ERROR - base_events.py:1758 - Task exception was never retrieved
future: <Task finished name='Task-262' coro=<Dispatcher._process_polling_updates() done, defined at /home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/stas/NotOnlyFansBot/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/stas/NotOnlyFansBot/src/bot.py", line 153, in process_get_photo_command
    await MaterialsManager().get_material_url(
  File "/home/stas/NotOnlyFansBot/src/materials_manager.py", line 41, in get_material_url
    href = href[0].json()[
IndexError: list index out of range
